version: '3'
services:
  mongodb:
    image: bitnami/mongodb:4.1.3
    environment:
      - MONGODB_ROOT_PASSWORD=123456
      - MONGODB_USERNAME=aaa
      - MONGODB_PASSWORD=123456
      - MONGODB_DATABASE=aaa
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/bitnami
